name: React Native Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Change to mobile-client directory
      #   run: cd mobile-client

      # - name: Install dependencies
      #   run: npm install

      - name: Run Jest tests
        working-directory: ./mobile-client
        run: npm run test
