name: React Native CI with Jest Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests (client)
        working-directory: mobile-client
        run: npm run test

  test-mobile-client:
    needs: test-client
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests (mobile-client)
        working-directory: mobile-client
        run: npm run test  # Adapt if needed

  # Additional jobs for web-client, server, and deployment
